version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        bin: server
        dir: /go/src/github.com/alr-lab/practical-test-pyramid-go
    command: ./server
    ports:
    - "8080:8080"
    networks:
    - app

  mysql:
    container_name: datastore
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --lower_case_table_names=0 --skip-innodb-adaptive-hash-index
    volumes:
    - mysql-data:/var/lib/mysql:cached
    ports:
    - "3306:3306"
    networks:
    - app

  mockapi:
    container_name: mockapi
    build:
      context: .
      dockerfile: docker/Dockerfile.mockapi
      args:
        bin: mockapi
        dir: /go/src/github.com/alr-lab/practical-test-pyramid-go
    command: ./mockapi
    ports:
    - "8081:8081"
    networks:
    - app

volumes:
  mysql-data:

networks:
  app:
    name: service
