name: Automated tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d --build
      - name: Unit tests
        run: docker exec -i app make test-unit
      - name: Integration tests
        run: docker exec -i app make test-integration
      - name: UI tests
        run: docker exec -i app make test-ui
      - name: End-to-end tests
        run: docker exec -i app make test-endtoend
